apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - mariadb-statefull.yaml
  - mariadb-headlesservice.yaml

patches:
  - path: todo-configmap-patch.yaml
    target:
      kind: ConfigMap
      name: todo-config
  - path: backend-delete-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend-init-patch.yaml         
    target:
      kind: Deployment
      name: frontend
