apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../stateful        # overlay 1 – כבר כולל base + StatefulSet
  - frontend-hpa.yaml  # משאב חדש – ה-HPA

patches:
  - path: frontend-resources-patch.yaml
    target:
      kind: Deployment
      name: frontend
