apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: todolist
        image: ghcr.io/bennyro-mta/todolist:1.10
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: MYSQL_HOST
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: MYSQL_DB
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: USER
        - name: MYSQL_TABLE
          valueFrom:
            configMapKeyRef:
              name: todo-config
              key: MYSQL_TABLE
