apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service  # Optional label; can stay as is
spec:
  selector:
    app: backend   # Must match backend pods label exactly
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP

