apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - mariadb-pvc.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - todo-configmap.yaml
  - mysql-secret.yaml
  - backup-pvc.yaml
  - mariadb-backup-cronjob.yaml
